name: line
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: 7.0.0
  flutter_bloc: 7.0.0
  equatable: 2.0.0
  fl_chart: ^0.35.0
  http: ^0.13.3
  shared_preferences: ^2.0.6
  geolocator: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Baloo
      fonts:
      - asset: assets/fonts/Baloo2-Regular.ttf
      - asset: assets/fonts/Baloo2-Bold.ttf
        
  
