function dataObject() {
    return setObjet();
}

function setObjet () {
    return {
        Monday:{
            averageDayTime:0,
            TotalVisits:0,
            Time:{
                0:{numberOfVisits:0, averageWait: 0},
                1:{numberOfVisits:0, averageWait: 0},
                2:{numberOfVisits:0, averageWait: 0},
                3:{numberOfVisits:0, averageWait: 0},
                4:{numberOfVisits:0, averageWait: 0},
                5:{numberOfVisits:0, averageWait: 0},
                6:{numberOfVisits:0, averageWait: 0},
                7:{numberOfVisits:0, averageWait: 0},
                8:{numberOfVisits:0, averageWait: 0},
                9:{numberOfVisits:0, averageWait: 0},
                10:{numberOfVisits:0, averageWait: 0},
                11:{numberOfVisits:0, averageWait: 0},
                12:{numberOfVisits:0, averageWait: 0},
                13:{numberOfVisits:0, averageWait: 0},
                14:{numberOfVisits:0, averageWait: 0},
                15:{numberOfVisits:0, averageWait: 0},
                16:{numberOfVisits:0, averageWait: 0},
                17:{numberOfVisits:0, averageWait: 0},
                18:{numberOfVisits:0, averageWait: 0},
                19:{numberOfVisits:0, averageWait: 0},
                20:{numberOfVisits:0, averageWait: 0},
                21:{numberOfVisits:0, averageWait: 0},
                22:{numberOfVisits:0, averageWait: 0},
                23:{numberOfVisits:0, averageWait: 0},

            }
        },
        Tuesday:{
            averageDayTime:0,
            TotalVisits:0,
            Time:{
                0:{numberOfVisits:0, averageWait: 0},
                1:{numberOfVisits:0, averageWait: 0},
                2:{numberOfVisits:0, averageWait: 0},
                3:{numberOfVisits:0, averageWait: 0},
                4:{numberOfVisits:0, averageWait: 0},
                5:{numberOfVisits:0, averageWait: 0},
                6:{numberOfVisits:0, averageWait: 0},
                7:{numberOfVisits:0, averageWait: 0},
                8:{numberOfVisits:0, averageWait: 0},
                9:{numberOfVisits:0, averageWait: 0},
                10:{numberOfVisits:0, averageWait: 0},
                11:{numberOfVisits:0, averageWait: 0},
                12:{numberOfVisits:0, averageWait: 0},
                13:{numberOfVisits:0, averageWait: 0},
                14:{numberOfVisits:0, averageWait: 0},
                15:{numberOfVisits:0, averageWait: 0},
                16:{numberOfVisits:0, averageWait: 0},
                17:{numberOfVisits:0, averageWait: 0},
                18:{numberOfVisits:0, averageWait: 0},
                19:{numberOfVisits:0, averageWait: 0},
                20:{numberOfVisits:0, averageWait: 0},
                21:{numberOfVisits:0, averageWait: 0},
                22:{numberOfVisits:0, averageWait: 0},
                23:{numberOfVisits:0, averageWait: 0},

            }
        },
        Wednesday:{
            averageDayTime:0,
            TotalVisits:0,
            Time:{
                0:{numberOfVisits:0, averageWait: 0},
                1:{numberOfVisits:0, averageWait: 0},
                2:{numberOfVisits:0, averageWait: 0},
                3:{numberOfVisits:0, averageWait: 0},
                4:{numberOfVisits:0, averageWait: 0},
                5:{numberOfVisits:0, averageWait: 0},
                6:{numberOfVisits:0, averageWait: 0},
                7:{numberOfVisits:0, averageWait: 0},
                8:{numberOfVisits:0, averageWait: 0},
                9:{numberOfVisits:0, averageWait: 0},
                10:{numberOfVisits:0, averageWait: 0},
                11:{numberOfVisits:0, averageWait: 0},
                12:{numberOfVisits:0, averageWait: 0},
                13:{numberOfVisits:0, averageWait: 0},
                14:{numberOfVisits:0, averageWait: 0},
                15:{numberOfVisits:0, averageWait: 0},
                16:{numberOfVisits:0, averageWait: 0},
                17:{numberOfVisits:0, averageWait: 0},
                18:{numberOfVisits:0, averageWait: 0},
                19:{numberOfVisits:0, averageWait: 0},
                20:{numberOfVisits:0, averageWait: 0},
                21:{numberOfVisits:0, averageWait: 0},
                22:{numberOfVisits:0, averageWait: 0},
                23:{numberOfVisits:0, averageWait: 0},

            }
        },
        Thursday:{
            averageDayTime:0,
            TotalVisits:0,
            Time:{
                0:{numberOfVisits:0, averageWait: 0},
                1:{numberOfVisits:0, averageWait: 0},
                2:{numberOfVisits:0, averageWait: 0},
                3:{numberOfVisits:0, averageWait: 0},
                4:{numberOfVisits:0, averageWait: 0},
                5:{numberOfVisits:0, averageWait: 0},
                6:{numberOfVisits:0, averageWait: 0},
                7:{numberOfVisits:0, averageWait: 0},
                8:{numberOfVisits:0, averageWait: 0},
                9:{numberOfVisits:0, averageWait: 0},
                10:{numberOfVisits:0, averageWait: 0},
                11:{numberOfVisits:0, averageWait: 0},
                12:{numberOfVisits:0, averageWait: 0},
                13:{numberOfVisits:0, averageWait: 0},
                14:{numberOfVisits:0, averageWait: 0},
                15:{numberOfVisits:0, averageWait: 0},
                16:{numberOfVisits:0, averageWait: 0},
                17:{numberOfVisits:0, averageWait: 0},
                18:{numberOfVisits:0, averageWait: 0},
                19:{numberOfVisits:0, averageWait: 0},
                20:{numberOfVisits:0, averageWait: 0},
                21:{numberOfVisits:0, averageWait: 0},
                22:{numberOfVisits:0, averageWait: 0},
                23:{numberOfVisits:0, averageWait: 0},

            }
        },
        Friday:{
            averageDayTime:0,
            TotalVisits:0,
            Time:{
                0:{numberOfVisits:0, averageWait: 0},
                1:{numberOfVisits:0, averageWait: 0},
                2:{numberOfVisits:0, averageWait: 0},
                3:{numberOfVisits:0, averageWait: 0},
                4:{numberOfVisits:0, averageWait: 0},
                5:{numberOfVisits:0, averageWait: 0},
                6:{numberOfVisits:0, averageWait: 0},
                7:{numberOfVisits:0, averageWait: 0},
                8:{numberOfVisits:0, averageWait: 0},
                9:{numberOfVisits:0, averageWait: 0},
                10:{numberOfVisits:0, averageWait: 0},
                11:{numberOfVisits:0, averageWait: 0},
                12:{numberOfVisits:0, averageWait: 0},
                13:{numberOfVisits:0, averageWait: 0},
                14:{numberOfVisits:0, averageWait: 0},
                15:{numberOfVisits:0, averageWait: 0},
                16:{numberOfVisits:0, averageWait: 0},
                17:{numberOfVisits:0, averageWait: 0},
                18:{numberOfVisits:0, averageWait: 0},
                19:{numberOfVisits:0, averageWait: 0},
                20:{numberOfVisits:0, averageWait: 0},
                21:{numberOfVisits:0, averageWait: 0},
                22:{numberOfVisits:0, averageWait: 0},
                23:{numberOfVisits:0, averageWait: 0},

            }
        },
        Saturday:{
            averageDayTime:0,
            TotalVisits:0,
            Time:{
                0:{numberOfVisits:0, averageWait: 0},
                1:{numberOfVisits:0, averageWait: 0},
                2:{numberOfVisits:0, averageWait: 0},
                3:{numberOfVisits:0, averageWait: 0},
                4:{numberOfVisits:0, averageWait: 0},
                5:{numberOfVisits:0, averageWait: 0},
                6:{numberOfVisits:0, averageWait: 0},
                7:{numberOfVisits:0, averageWait: 0},
                8:{numberOfVisits:0, averageWait: 0},
                9:{numberOfVisits:0, averageWait: 0},
                10:{numberOfVisits:0, averageWait: 0},
                11:{numberOfVisits:0, averageWait: 0},
                12:{numberOfVisits:0, averageWait: 0},
                13:{numberOfVisits:0, averageWait: 0},
                14:{numberOfVisits:0, averageWait: 0},
                15:{numberOfVisits:0, averageWait: 0},
                16:{numberOfVisits:0, averageWait: 0},
                17:{numberOfVisits:0, averageWait: 0},
                18:{numberOfVisits:0, averageWait: 0},
                19:{numberOfVisits:0, averageWait: 0},
                20:{numberOfVisits:0, averageWait: 0},
                21:{numberOfVisits:0, averageWait: 0},
                22:{numberOfVisits:0, averageWait: 0},
                23:{numberOfVisits:0, averageWait: 0},

            }
        },
        Sunday:{
            averageDayTime:0,
            TotalVisits:0,
            Time:{
                0:{numberOfVisits:0, averageWait: 0},
                1:{numberOfVisits:0, averageWait: 0},
                2:{numberOfVisits:0, averageWait: 0},
                3:{numberOfVisits:0, averageWait: 0},
                4:{numberOfVisits:0, averageWait: 0},
                5:{numberOfVisits:0, averageWait: 0},
                6:{numberOfVisits:0, averageWait: 0},
                7:{numberOfVisits:0, averageWait: 0},
                8:{numberOfVisits:0, averageWait: 0},
                9:{numberOfVisits:0, averageWait: 0},
                10:{numberOfVisits:0, averageWait: 0},
                11:{numberOfVisits:0, averageWait: 0},
                12:{numberOfVisits:0, averageWait: 0},
                13:{numberOfVisits:0, averageWait: 0},
                14:{numberOfVisits:0, averageWait: 0},
                15:{numberOfVisits:0, averageWait: 0},
                16:{numberOfVisits:0, averageWait: 0},
                17:{numberOfVisits:0, averageWait: 0},
                18:{numberOfVisits:0, averageWait: 0},
                19:{numberOfVisits:0, averageWait: 0},
                20:{numberOfVisits:0, averageWait: 0},
                21:{numberOfVisits:0, averageWait: 0},
                22:{numberOfVisits:0, averageWait: 0},
                23:{numberOfVisits:0, averageWait: 0},

            }
        },
    }
}

module.exports = dataObject;
